In [1]:
import numpy as np

In [4]:
arr = np.arange(0, 6)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
np.ones(20).astype(int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
np.ones(20).astype(int).reshape(4, 5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
arr = np.ones(100).astype(int).reshape(10, 10)
arr *= 255
arr

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

In [10]:
np.zeros(12).astype(int).reshape(3, 4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.arange(1, 4).astype(int)

array([1, 2, 3])

In [15]:
arr = np.array([1, 2, 3])
arr.dtype

dtype('int64')

In [16]:
arr = np.array(['1', '2', '3'])
arr.dtype
# 'U1'은 1 바이트 문자열이라는 의미.

dtype('<U1')

In [19]:
arr = np.array([1, 2, 3], np.dtype(np.int16))
arr

array([1, 2, 3], dtype=int16)

In [20]:
a = np.array([255, 300, 128], dtype=np.uint8)
a
# 'uint8'은 부호 없는 8비트 정수. 0부터 2**8-1 범위의 수를 표현할 수 있음.
# 300은 'uint8'이 표현할 수 있는 범위를 넘기 때문에 잘못된 값이 출력됨.

array([255,  44, 128], dtype=uint8)