In [1]:
import numpy as np

In [2]:
data = [1, 2, 3]
arr = np.array(data) * 10
arr

array([10, 20, 30])

In [3]:
data = [1, 2, 3]
arr = np.array(data) ** 2
arr

array([1, 4, 9])

In [4]:
data = [1, 2, 3]
arr = np.array(data) ** (1/2)
arr

array([1.        , 1.41421356, 1.73205081])

In [7]:
score = np.array([
    [10, 20], # 중간고사
    [14, 16]  # 기말고사
])
score.mean(axis=0)

array([12., 18.])

In [9]:
score = np.array([
    [10, 20], # 중간고사
    [14, 16]  # 기말고사
])

score.std(axis=1)

array([5., 1.])