In [1]:
import numpy as np

In [4]:
arr = np.array([1.1, 2.1, 3.1], np.dtype(np.int32))
arr

array([1, 2, 3], dtype=int32)

In [6]:
#### linspace는 공부해야할 듯 함.
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [8]:
arr = np.arange(9).reshape(3, 3)
arr[2]

array([6, 7, 8])

In [13]:
arr = np.arange(9).reshape(3, 3)
arr[:,1]

array([1, 4, 7])

In [17]:
arr = np.arange(25).reshape(5, 5)
arr
arr[3, 2]
# arr[3][2]

17

In [23]:
arr = np.arange(5)
arr[[1,3]]

array([1, 3])

In [24]:
arr = np.arange(25).reshape(5, 5)
arr
arr[1, 1:]

array([6, 7, 8, 9])

In [26]:
arr = np.arange(25).reshape(5, 5)
arr[:, :2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [29]:
arr = np.arange(25).reshape(5, 5)
arr[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [54]:
arr = np.arange(25).reshape(5, 5)
arr[::4,::3]

array([[ 0,  3],
       [20, 23]])